rest-config2:
  string-property: Monday
  boolean-property: true
  integer-property: 23
  encoded-property: ZW5jb2RlZCBwcm9wZXJ0eQ==

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23
  encoded-property: ZW5jb2RlZCBwcm9wZXJ0eQ==